### ISSUE TITLE
class ListenerBase(metaclass=abc.ABCMeta): - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by twsgermany** [cceremuga/pypacket#3]
```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    pypacket_receiver.start()
  File "/root/pypacket/pypacket/base/receiver.py", line 40, in start
    listener = self.config.listener()
  File "/root/pypacket/pypacket/base/configuration.py", line 33, in listener
    module = importlib.import_module(self.data['listener']['module'])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/pypacket/pypacket/base/rtl_listener.py", line 2, in <module>
    from pypacket.base.listener import ListenerBase
  File "/root/pypacket/pypacket/base/listener.py", line 3
    class ListenerBase(metaclass=abc.ABCMeta):

```

Do you know the problem?

**Comment by cceremuga** [comment]
Resolved with update to python 3 dependencies, was an outdated 2.7 syntax.

**Comment by dermodmaster** [comment]
Thanks :)
